# This file is a template, and might need editing before it works on your project.
image: elixir:1.4

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - postgres:9.6

variables:
  MIX_ENV: "test"

before_script:
  - apt-get update
  - apt-get install -y postgresql-client
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix ecto.create

mix:
  script:
  - mix test
  - mix credo --strict
  - mix dogma
